/* Automatically generated by wasm2c */
#ifndef EXAMPLE_H_GENERATED_
#define EXAMPLE_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_example {
  wasm_rt_memory_t w2c_memory;
} w2c_example;

void wasm2c_example_instantiate(w2c_example*);
void wasm2c_example_free(w2c_example*);
wasm_rt_func_type_t wasm2c_example_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: 'fib' */
u32 w2c_example_fib(w2c_example*, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_example_memory(w2c_example* instance);

#ifdef __cplusplus
}
#endif

#endif  /* EXAMPLE_H_GENERATED_ */
